[14-Apr-2025 22:59:17 UTC] PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Yaml\Exception\RuntimeException" not found in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/DumpException.php:19
Stack trace:
#0 {main}
  thrown in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/DumpException.php on line 19
[14-Apr-2025 22:59:20 UTC] PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Yaml\Exception\RuntimeException" not found in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/ParseException.php:19
Stack trace:
#0 {main}
  thrown in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/ParseException.php on line 19
[14-Apr-2025 22:59:22 UTC] PHP Fatal error:  Uncaught Error: Interface "Symfony\Component\Yaml\Exception\ExceptionInterface" not found in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/RuntimeException.php:19
Stack trace:
#0 {main}
  thrown in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/RuntimeException.php on line 19
[24-Apr-2025 10:45:57 UTC] PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Yaml\Exception\RuntimeException" not found in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/DumpException.php:19
Stack trace:
#0 {main}
  thrown in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/DumpException.php on line 19
[24-Apr-2025 10:46:01 UTC] PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Yaml\Exception\RuntimeException" not found in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/ParseException.php:19
Stack trace:
#0 {main}
  thrown in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/ParseException.php on line 19
[24-Apr-2025 10:46:02 UTC] PHP Fatal error:  Uncaught Error: Interface "Symfony\Component\Yaml\Exception\ExceptionInterface" not found in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/RuntimeException.php:19
Stack trace:
#0 {main}
  thrown in /home/softoroa/flight.softnear.com/vendor/symfony/yaml/Exception/RuntimeException.php on line 19
